apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.tenant }}-quota
spec:
  hard:
    pods: {{ .Values.quota.pods | quote }}
    limits.cpu: {{ .Values.quota.cpu | quote }}
    limits.memory: {{ .Values.quota.memory | quote }}
